apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rx7u7wa1f-java-quarkus
  janus-idp.io/tekton: rx7u7wa1f-java-quarkus
  backstage.io/kubernetes-id: rx7u7wa1f-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rx7u7wa1f-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
